# Generated by Django 2.2.2 on 2020-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='coordinator_url',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='events',
            name='gallery_url',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
