# Generated by Django 2.2.2 on 2020-04-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20200415_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='coordinator_url',
        ),
        migrations.RemoveField(
            model_name='events',
            name='gallery_url',
        ),
    ]
