# Generated by Django 2.2.2 on 2020-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20200415_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='coordinator_url',
            field=models.TextField(blank=True, default='Y', null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='gallery_url',
            field=models.TextField(blank=True, default='Y', null=True),
        ),
    ]
