# Generated by Django 2.2.2 on 2020-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_auto_20200415_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default='18'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='college',
            field=models.TextField(default='IIST'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.TextField(default='dont be sexist'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile_no',
            field=models.TextField(default='1234567890'),
        ),
    ]
