# Generated by Django 2.2.2 on 2020-05-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_auto_20200416_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('ONL', 'online'), ('OFF', 'offline'), ('WOR', 'workshops'), ('MAJ', 'majorEvents'), ('OFF', 'offline')], max_length=3, null=True),
        ),
    ]
