# Generated by Django 2.2.2 on 2020-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_events_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('ONL', 'online'), ('OFF', 'offline'), ('WOR', 'workshops'), ('MAJ', 'majorEvents'), ('QUZ', 'quiz')], max_length=3, null=True),
        ),
    ]
