# Generated by Django 2.2.2 on 2020-05-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_auto_20200529_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.TextField(default='must be same with the usermodel TextField'),
        ),
    ]
