# Generated by Django 2.2.2 on 2020-05-31 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0011_auto_20190223_2138'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(choices=[('WEB', 'webbed'), ('MAT', 'mathematrix'), ('CUB', 'cubbed'), ('AST', 'astronomy')], max_length=3)),
                ('counter', models.IntegerField(default=1)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(choices=[('WEB', 'webbed'), ('MAT', 'mathematrix'), ('CUB', 'cubbed'), ('AST', 'astronomy')], max_length=3)),
                ('unique_id', models.TextField(default='eg- wb1', unique=True)),
                ('question_no', models.IntegerField(default=1)),
                ('question', models.TextField(default='question')),
                ('answer', models.TextField(default='answer')),
                ('question_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionimage', to='photologue.Gallery')),
            ],
        ),
    ]
