# Generated by Django 2.2.2 on 2020-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_question_userquizdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='queation_img_url',
            field=models.TextField(null=True),
        ),
    ]
