# Generated by Django 2.2.2 on 2020-06-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_question_queation_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizdata',
            old_name='username',
            new_name='user',
        ),
    ]
